# CC=g++-10
# std=c++2a
# CFLAGS=-I.

ColliderSingleCore.o: ColliderSingleCore.cpp 
	g++-10 -std=c++2a -o ColliderSingleCore.o ColliderSingleCore.cpp


testSC.o: ColliderSingleCore.cpp 
	g++-10 -std=c++2a -o testSC.o ColliderSingleCore.cpp