# CC=g++-10
# std=c++2a
# CFLAGS=-I.

timing_test.o: timing.hpp timing_test.cpp
	g++-10 -std=c++2a -o timing_test.o timing_test.cpp


# test: ColliderSingleCore.cpp 
# 	g++-10 -std=c++2a -o testSC.o ColliderSingleCore.cpp

clean:
	rm -f *.o
